### ISSUE TITLE
API Rewrite

### ISSUE THREAD

**Issue by timrwood** [moment/moment-timezone#87]
This is all part of the rewrite I started in #82. I was working off a gist earlier, but thought it would be good to expose this for other comments.
# Formats

``` js
// Packed
"America/Los_Angeles|PST PDT|70 60|010101010101|-h234i0 fgd0 wef0 fgd0 wef0 fgd0 wef0"

// Unpacked
{
    name    : "America/Los_Angeles",
    abbrs   : ["PST", "PDT", "PST", "PDT", "PST", "PDT", "PST", "PDT", "PST", "PDT"],
    offsets : [420, 480, 420, 480, 420, 480, 420, 480, 420, 480, 420, 480, 420, 480],
    untils  : [-134089073429, -134074893883, -13407683724, -134074372626, -134074937463, -134074937463]
}
```
# Data utils

``` js
// in moment-timezone.js
moment.tz.unpack(packed string) > unpacked object
moment.tz.unpackBase60(string) > number

// in moment-timezone-utils.js
moment.tz.pack(unpacked object) > packed string
moment.tz.packBase60(number, precision) > string
moment.tz.filterYear(unpacked object, min, max) > new unpacked object
```
# External API

``` js
moment.tz.add(packed string[])
moment.tz.add(packed string)
moment.tz.link(nameA, nameB)
moment.tz.link("nameA|nameB")
moment.tz.link("nameA|nameB"[])
moment.tz.zoneNames() > Zone[]
moment.tz.zone(name) > Zone || undefined
moment.tz._zones = {} // expose internal cache
moment.tz._links = {} // expose internal cache
```
# Zone API

``` js
moment.tz.Zone(packed string)
moment.tz.Zone.prototype.offset(moment or timestamp)
moment.tz.Zone.prototype.abbr(moment or timestamp)
moment.tz.Zone.prototype._index(moment or timestamp)
```
# Interaction with moment.js

``` js
moment.tz(..., zone name)
moment.fn.tz(zone name)
```
# Folder structure

```
/build
    moment-timezone.min.js
    moment-timezone-utils.min.js
    moment-timezone-with-data.js
    moment-timezone-with-data.min.js
/data
    /source > git submodule of eggert/tz
    /packed
        latest.json
        2014a.json
        2014b.json
    /unpacked
        2014a.json
        2014b.json
    /zdump
        2014a.json
        2014b.json
/tasks
    /helpers
        zic.js
        zdump.js
        dedupe.js
    build-data.js
    build-tests.js
    build-zdump.js
/tests
    /zones
        /africa
        /america
        /...
    /moment-timezone
        add.js
        link.js
        moment-tz.js
        moment-fn-tz.js
        unpack.js
        unpack-base-62.js
        zone.js
        zone-abbr-for.js
        zone-offset-for.js
        zones.js
    /moment-timezone-utils
        pack.js
        pack-base-62.js
    helpers.js
moment-timezone.js
moment-timezone-utils.js
```
# TODO
- [x] Move zone tests to /tests/zones
- [x] Move moment-timezone.json to /data/packed/latest.json
- [x] Write moment.tz.unpackBase60 + tests
- [x] Write moment.tz.unpack + tests
- [x] Write moment.tz.packBase60 + tests
- [x] Write moment.tz.pack + tests
- [x] Write moment.tz.Zone + tests
- [x] Write moment.tz.Zone#_indexFor + tests
- [x] Write moment.tz.Zone#offsetFor + tests
- [x] Write moment.tz.Zone#abbrFor + tests
- [x] Write moment.tz.add + tests
- [x] Write moment.tz.link + tests
- [x] Write moment.tz.zoneNames + tests
- [x] Write moment.tz.zone + tests
- [x] Write moment.tz.filterYear + tests
- [x] Write data-download task (iana.org/time-zones > temp/download/northamerica)
- [x] Write data-zic task (temp/download/northamerica > temp/zic/america/los_angeles)
- [x] Write data-zdump task (temp/zic/america/los_angeles > temp/zdump/america/los_angeles.zdump)
- [x] Write data-collect task (temp/zdump/america/los_angeles > data/zdump/*.json)
- [x] Write data-dedupe task (data/zdump/_.json > data/unpacked/_.json)
- [x] Write data-pack task (data/unpacked/_.json > data/packed/_.json)
- [x] Write data-tests task (data/zdump/*.json > tests/zones/america/los_angeles.js)
